### ISSUE TITLE
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration

### ISSUE THREAD

**Issue by navanjr** [adityar15/nuxt3socket#1]
server errors when a client connects...

```
[nitro] [dev] [uncaughtException] Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:363:13)
    at WebSocketServer.handleUpgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:339:10)
    at Server.upgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:114:16)
    at Server.emit (node:events:539:35)
    at onParserExecuteCommon (node:_http_server:732:14)
    at onParserExecute (node:_http_server:646:3)
```

Enjoyed your video. Thank you for sharing.

**Comment by cliqer** [comment]
I have the same problem.
Cloned the repo, yarn and error when clients connect.
Any solutions?

**Comment by PrimalDjinn** [comment]
> 

Hey, check o

> server errors when a client connects...
> 
> ```
> [nitro] [dev] [uncaughtException] Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
>     at WebSocketServer.completeUpgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:363:13)
>     at WebSocketServer.handleUpgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:339:10)
>     at Server.upgrade (/Users/nate/source/nuxt3socket/node_modules/ws/lib/websocket-server.js:114:16)
>     at Server.emit (node:events:539:35)
>     at onParserExecuteCommon (node:_http_server:732:14)
>     at onParserExecute (node:_http_server:646:3)
> ```
> 
> Enjoyed your video. Thank you for sharing.

Hey, check out my updated repo https://github.com/kgarchie/nuxt3socket
